/** @vitest-environment node */
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { games } from './games'
import { officialCatalog } from './generated/officialCatalog'

const root = process.cwd()
const gamesDir = join(root, 'public', 'games')
const generatorPath = join(root, 'scripts', 'generate-games.mjs')
const catalogPath = join(root, 'src', 'generated', 'officialCatalog.ts')

const REQUIRED_BRIDGE_SNIPPETS = [
  'gamescroll:ready',
  'gamescroll:start',
  'gamescroll:pause',
  'gamescroll:score',
  'gamescroll:died',
  'gamescroll:swipe-next',
  'gamescroll:swipe-prev',
  'onFail',
]

describe('catalog integrity', () => {
  it('every catalog game has a generated HTML file', () => {
    for (const game of games) {
      const path = join(gamesDir, `${game.id}.html`)
      expect(existsSync(path), `missing ${game.src}`).toBe(true)
    }
  })

  it('every public game HTML is listed in the catalog', () => {
    const files = readdirSync(gamesDir).filter((f) => f.endsWith('.html'))
    const catalogIds = new Set(games.map((g) => g.id))
    for (const file of files) {
      const id = file.replace(/\.html$/, '')
      expect(catalogIds.has(id), `orphan public/games/${file}`).toBe(true)
    }
    expect(files).toHaveLength(games.length)
  })

  it('generated games include the host bridge contract', () => {
    const sample = readFileSync(join(gamesDir, `${games[0].id}.html`), 'utf8')
    for (const snippet of REQUIRED_BRIDGE_SNIPPETS) {
      expect(sample.includes(snippet), `missing bridge snippet: ${snippet}`).toBe(
        true,
      )
    }
  })

  it('culled games are not shipped', () => {
    for (const id of ['orbit', 'light', 'helix', 'shield']) {
      expect(existsSync(join(gamesDir, `${id}.html`))).toBe(false)
      expect(games.some((g) => g.id === id)).toBe(false)
      expect(officialCatalog.some((g) => g.id === id)).toBe(false)
    }
  })

  it('ships an emitted officialCatalog that matches the feed catalog ids', () => {
    expect(existsSync(catalogPath)).toBe(true)
    expect(readFileSync(catalogPath, 'utf8')).toContain(
      'Generated by `node scripts/generate-games.mjs`',
    )
    expect(officialCatalog.map((e) => e.id)).toEqual(games.map((g) => g.id))
    expect(officialCatalog.length).toBeGreaterThan(0)
  })

  it('generator defines title, tip, and bg for every catalog id', () => {
    const src = [
      readFileSync(generatorPath, 'utf8'),
      readFileSync(join(root, 'scripts', 'wave1-games.mjs'), 'utf8'),
      readFileSync(join(root, 'scripts', 'wave2-games.mjs'), 'utf8'),
      readFileSync(join(root, 'scripts', 'wave3-games.mjs'), 'utf8'),
    ].join('\n')
    for (const entry of officialCatalog) {
      expect(src).toContain(`${entry.id}: {`)
      expect(src).toContain(`title: '${entry.title}'`)
      expect(src).toContain(`tip: '${entry.tip}'`)
    }
  })
})
